// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANaf6rqKebJKuZioVJFLybSpI1qFBZUZE',
    appId: '1:1026061594392:web:1fc39ed43ef65ad6bab86d',
    messagingSenderId: '1026061594392',
    projectId: 'to-do-database-c0355',
    authDomain: 'to-do-database-c0355.firebaseapp.com',
    storageBucket: 'to-do-database-c0355.appspot.com',
    measurementId: 'G-FRHD7DY9FD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAil3QuPZrlxWA2k2SGzk7Xntk5TSFyuX4',
    appId: '1:1026061594392:android:0976dfe3bc323ac3bab86d',
    messagingSenderId: '1026061594392',
    projectId: 'to-do-database-c0355',
    storageBucket: 'to-do-database-c0355.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBz7Wp54jz0BcFkvDLFSe5wx9NVbPKmF_A',
    appId: '1:1026061594392:ios:8c0ef54376f6a54fbab86d',
    messagingSenderId: '1026061594392',
    projectId: 'to-do-database-c0355',
    storageBucket: 'to-do-database-c0355.appspot.com',
    iosBundleId: 'com.example.todoappfirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBz7Wp54jz0BcFkvDLFSe5wx9NVbPKmF_A',
    appId: '1:1026061594392:ios:b001d386fe4bc890bab86d',
    messagingSenderId: '1026061594392',
    projectId: 'to-do-database-c0355',
    storageBucket: 'to-do-database-c0355.appspot.com',
    iosBundleId: 'com.example.todoappfirebase.RunnerTests',
  );
}
